### ISSUE TITLE
The artist already created .ani files.

### ISSUE THREAD

**Issue by 12beesinatrenchcoat** [mellowagain/kiawa-cursor#1]
I think they did it an hour after you created the repository. They're crisper as well. Sorry about that.
https://twitter.com/growowling/status/1510623136558985221?s=20&t=cvJMZ555eGVHYFHTkdgLOw
https://drive.google.com/drive/folders/1ZQmPT_25MWa4-lhcU7nJNMWF7hBQUomp

**Comment by mellowagain** [comment]
Yea, I saw that. Thanks for the heads up. I made the cursor file before the artist uploaded the official ones and just wanted to share it. I suggest people use that artist's original cursor file. I'll update the README to reflect this.
